generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Version
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          version
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id:                       {label:Id}
        descripcion:              {label:Descripción}
        plc:                      {label:PLC}
      list:    
        title:                    Listado de Versiones de Placas
        sort:                     [id, asc]
        display:                  [id, descripcion, plc]
        object_actions:
          #_delete:                { label: 'Borrar' , params: confirm=¿Está seguro?  }
          _edit:                  { label: 'Editar' }
        batch_actions:            []
          #_delete:                { label: 'Borrar' , params: confirm=¿Está seguro?  }
        actions:                  []
          #_new:                   { label: 'Crear nuevo'  }  
      filter:  ~
      form:    ~
      edit:    
        title:                    Editando Versión de Placa "<strong>%%descripcion%% (%%id%%)</strong>"
      new:     ~
