<?php

/**
 * ComponentesetiquetasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComponentesetiquetasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComponentesetiquetasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Componentesetiquetas');
    }
}