<?php

/**
 * EnsayoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnsayoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnsayoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ensayo');
    }
}