<?php

/**
 * EnsayoAltoPotencialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnsayoAltoPotencialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnsayoAltoPotencialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnsayoAltoPotencial');
    }
}