<?php

/**
 * EnsayosrealizadosiduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnsayosrealizadosiduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnsayosrealizadosiduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ensayosrealizadosidu');
    }
}