<?php

/**
 * EnsayoFallaControladaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnsayoFallaControladaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnsayoFallaControladaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnsayoFallaControlada');
    }
}