<?php

/**
 * EtiquetasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtiquetasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtiquetasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etiquetas');
    }
}