<?php

/**
 * EtiquetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtiquetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtiquetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etiqueta');
    }
}