<?php

/**
 * FallaControladaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FallaControladaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FallaControladaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FallaControlada');
    }
}