<?php

/**
 * FallasiduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FallasiduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FallasiduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fallasidu');
    }
}