<?php

/**
 * FallasoduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FallasoduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FallasoduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fallasodu');
    }
}