<?php

/**
 * InfoensayosresetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoensayosresetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoensayosresetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Infoensayosreset');
    }
}