<?php

/**
 * ItemetiquetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemetiquetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemetiquetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Itemetiqueta');
    }
}