<?php

/**
 * LogIduOduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogIduOduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogIduOduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogIduOdu');
    }
}