<?php

/**
 * ModelosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModelosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Modelos');
    }
}