<?php

/**
 * NumeroserieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NumeroserieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NumeroserieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Numeroserie');
    }
}