<?php

/**
 * ParametrosensayosiduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametrosensayosiduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametrosensayosiduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parametrosensayosidu');
    }
}