<?php

/**
 * ParametrosensayosoduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametrosensayosoduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametrosensayosoduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parametrosensayosodu');
    }
}