<?php

/**
 * PlacaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlacaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlacaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Placa');
    }
}