<?php

/**
 * ReimpresionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReimpresionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReimpresionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reimpresiones');
    }
}