<?php

/**
 * VersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Version');
    }
}