<?php

/**
 * VersionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VersionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VersionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Versiones');
    }
}