# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  sf_guard_plugin:
    routes_register: false 
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         CARRIER IDU ODU & PCB
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    categories:
      IDU ODU:
        items:
          Listado de usuarios:
            credentials:  [superadmin]
            url:          user_profile
            image:        users.png
          Nuevo usuario:
            credentials:  [superadmin]
            url:          user_profile/new
            image:        user1_add.png
          Listado de Modelos:
            credentials:  [superadmin]
            url:          modelos
            image:        index.png
          Listado de Referencias(CT):
            credentials:  [superadmin]
            url:          caracteristicastecnicasequipos
            image:        text_rich.png
          Par치metros de Ensayos IDU:
            credentials:  [superadmin]
            url:          parametrosensayosidu
            image:        potion_blue.png
          Par치metros de Ensayos ODU:
            credentials:  [superadmin]
            url:          parametrosensayosodu
            image:        potion_red.png
          Ensayos IDU:
            credentials:  [superadmin]
            url:          ensayosrealizadosidu
            image:        bullet_triangle_blue.png
          Ensayos ODU:
            credentials:  [superadmin]
            url:          ensayosrealizadosodu
            image:        bullet_triangle_red.png
          Ensayos HiPot:
            credentials:  [superadmin]
            url:          ensayo_alto_potencial
            image:        plug.png
          Logs de RunTest IDU/ODU:
            credentials:  [superadmin]
            url:          log_idu_odu
            image:        note_pinned.png
          # Ensayos Fallas controladas:
            # credentials:  [superadmin]
            # url:          ensayo_falla_controlada
            # image:        breakpoint_run.png
          Fallas controladas:
            credentials:  [superadmin]
            url:          falla_controlada
            image:        breakpoint_delete.png
      PCB:
        items:
          Placas:
            credentials:  [superadmin]
            url:          placa
            image:        PCI-card.png
          # Par치metros de ensayo:
            # credentials:  [superadmin]
            # url:          ensayoparametro
            # image:        potion_green.png
          Ensayos (configuraci칩n):
            credentials:  [superadmin]
            url:          ensayo
            image:        potion_green.png 
            #image:        PCI-card_preferences.png
          Ensayos Realizados:
            credentials:  [superadmin]
            url:          resultadoensayo
            image:        bullet_triangle_green.png
          Versiones de Placa:
            credentials:  [superadmin]
            url:          version
            image:        rubberstamp.png
          Etiquetas:
            credentials:  [superadmin]
            url:          etiqueta
            image:        document.png