connection: pcb
# PCB
Ensayo:
  connection: pcb
  tableName: ensayo
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Ensayoparametro:
      local: id
      foreign: ensayoid
      type: many
    Placa:
      local: id
      foreign: ensayoid
      type: many
Ensayoparametro:
  connection: pcb
  tableName: ensayoparametro
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    tag:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    paso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ensayoid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Ensayo:
      local: ensayoid
      foreign: id
      type: one
Etiqueta:
  connection: pcb
  tableName: etiqueta
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Itemetiqueta:
      local: id
      foreign: etiquetaid
      type: many
    Placa:
      local: id
      foreign: etiquetaid
      type: many
Itemetiqueta:
  connection: pcb
  tableName: itemetiqueta
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    font:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    size:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    bold:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    italic:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    xini:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    xfin:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    yini:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    yfin:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    variable:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rot:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    alignh:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    alignv:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    etiquetaid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    valor:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
  relations:
    Etiqueta:
      local: etiquetaid
      foreign: id
      type: one
Numeroserie:
  connection: pcb
  tableName: numeroserie
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    tipo:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    numero:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    maximo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    minimo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    prefijo:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sufijo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Placa:
  connection: pcb
  tableName: placa
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    codigo:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    extra1:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    extra2:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    extra3:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ensayoid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    etiquetaid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    versionid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Ensayo:
      local: ensayoid
      foreign: id
      type: one
    Etiqueta:
      local: etiquetaid
      foreign: id
      type: one
    Version:
      local: versionid
      foreign: id
      type: one
    Resultadoensayo:
      local: id
      foreign: placaid
      type: many
Resultadoensayo:
  connection: pcb
  tableName: resultadoensayo
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ensayook:
      type: integer(1)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    error:
      type: string(2048)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tension5v:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tension12v:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tensioncorr:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    velocidades:
      type: string(1024)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    numeroserie:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    placaid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    observaciones:
      type: string(2048)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dcf:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    paso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Placa:
      local: placaid
      foreign: id
      type: one
Serie:
  connection: doctrine
  tableName: serie
  columns:
    serie_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    serie_tipo:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    serie_numero:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    serie_maximo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    serie_minimo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    serie_prefijo:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    serie_sufijo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
Version:
  connection: pcb
  tableName: version
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    descripcion:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    plc:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Placa:
      local: id
      foreign: versionid
      type: many
      