<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Caracteristicastecnicasequipos', 'doctrine');

/**
 * BaseCaracteristicastecnicasequipos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $caracteristicastecnicasequipos_id
 * @property integer $caracteristicastecnicasequipos_version
 * @property string $caracteristicastecnicasequipos_descripcion1
 * @property string $caracteristicastecnicasequipos_descripcion2
 * @property string $caracteristicastecnicasequipos_descripcion3
 * @property string $caracteristicastecnicasequipos_descripcion4
 * @property string $caracteristicastecnicasequipos_descripcion5
 * @property string $caracteristicastecnicasequipos_descripcion6
 * @property string $caracteristicastecnicasequipos_tensionnominal
 * @property string $caracteristicastecnicasequipos_frecuencia
 * @property string $caracteristicastecnicasequipos_potenciamaxima
 * @property string $caracteristicastecnicasequipos_corrientemaxima
 * @property string $caracteristicastecnicasequipos_carga
 * @property string $caracteristicastecnicasequipos_presion
 * @property string $caracteristicastecnicasequipos_capacidadfrio
 * @property string $caracteristicastecnicasequipos_potencianominalfrio
 * @property string $caracteristicastecnicasequipos_corrientenominalfrio
 * @property string $caracteristicastecnicasequipos_peso
 * @property string $caracteristicastecnicasequipos_capacidadcalor
 * @property string $caracteristicastecnicasequipos_potencianominalcalor
 * @property string $caracteristicastecnicasequipos_corrientenominalcalor
 * @property string $caracteristicastecnicasequipos_err
 * @property integer $caracteristicastecnicasequipos_esidu
 * @property string $caracteristicastecnicasequipos_nombre
 * @property integer $caracteristicastecnicasequipos_idparametros
 * @property integer $caracteristicastecnicasequipos_idparametros_idu
 * @property integer $caracteristicastecnicasequipos_idparametros_odu
 * @property integer $es_activo
 * @property integer $id
 * @property Parametrosensayosidu $Parametrosensayosidu
 * @property Parametrosensayosodu $Parametrosensayosodu
 * @property Doctrine_Collection $Modelos
 * 
 * @method integer                        getCaracteristicastecnicasequiposId()                     Returns the current record's "caracteristicastecnicasequipos_id" value
 * @method integer                        getCaracteristicastecnicasequiposVersion()                Returns the current record's "caracteristicastecnicasequipos_version" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion1()           Returns the current record's "caracteristicastecnicasequipos_descripcion1" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion2()           Returns the current record's "caracteristicastecnicasequipos_descripcion2" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion3()           Returns the current record's "caracteristicastecnicasequipos_descripcion3" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion4()           Returns the current record's "caracteristicastecnicasequipos_descripcion4" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion5()           Returns the current record's "caracteristicastecnicasequipos_descripcion5" value
 * @method string                         getCaracteristicastecnicasequiposDescripcion6()           Returns the current record's "caracteristicastecnicasequipos_descripcion6" value
 * @method string                         getCaracteristicastecnicasequiposTensionnominal()         Returns the current record's "caracteristicastecnicasequipos_tensionnominal" value
 * @method string                         getCaracteristicastecnicasequiposFrecuencia()             Returns the current record's "caracteristicastecnicasequipos_frecuencia" value
 * @method string                         getCaracteristicastecnicasequiposPotenciamaxima()         Returns the current record's "caracteristicastecnicasequipos_potenciamaxima" value
 * @method string                         getCaracteristicastecnicasequiposCorrientemaxima()        Returns the current record's "caracteristicastecnicasequipos_corrientemaxima" value
 * @method string                         getCaracteristicastecnicasequiposCarga()                  Returns the current record's "caracteristicastecnicasequipos_carga" value
 * @method string                         getCaracteristicastecnicasequiposPresion()                Returns the current record's "caracteristicastecnicasequipos_presion" value
 * @method string                         getCaracteristicastecnicasequiposCapacidadfrio()          Returns the current record's "caracteristicastecnicasequipos_capacidadfrio" value
 * @method string                         getCaracteristicastecnicasequiposPotencianominalfrio()    Returns the current record's "caracteristicastecnicasequipos_potencianominalfrio" value
 * @method string                         getCaracteristicastecnicasequiposCorrientenominalfrio()   Returns the current record's "caracteristicastecnicasequipos_corrientenominalfrio" value
 * @method string                         getCaracteristicastecnicasequiposPeso()                   Returns the current record's "caracteristicastecnicasequipos_peso" value
 * @method string                         getCaracteristicastecnicasequiposCapacidadcalor()         Returns the current record's "caracteristicastecnicasequipos_capacidadcalor" value
 * @method string                         getCaracteristicastecnicasequiposPotencianominalcalor()   Returns the current record's "caracteristicastecnicasequipos_potencianominalcalor" value
 * @method string                         getCaracteristicastecnicasequiposCorrientenominalcalor()  Returns the current record's "caracteristicastecnicasequipos_corrientenominalcalor" value
 * @method string                         getCaracteristicastecnicasequiposErr()                    Returns the current record's "caracteristicastecnicasequipos_err" value
 * @method integer                        getCaracteristicastecnicasequiposEsidu()                  Returns the current record's "caracteristicastecnicasequipos_esidu" value
 * @method string                         getCaracteristicastecnicasequiposNombre()                 Returns the current record's "caracteristicastecnicasequipos_nombre" value
 * @method integer                        getCaracteristicastecnicasequiposIdparametros()           Returns the current record's "caracteristicastecnicasequipos_idparametros" value
 * @method integer                        getCaracteristicastecnicasequiposIdparametrosIdu()        Returns the current record's "caracteristicastecnicasequipos_idparametros_idu" value
 * @method integer                        getCaracteristicastecnicasequiposIdparametrosOdu()        Returns the current record's "caracteristicastecnicasequipos_idparametros_odu" value
 * @method integer                        getEsActivo()                                             Returns the current record's "es_activo" value
 * @method integer                        getId()                                                   Returns the current record's "id" value
 * @method Parametrosensayosidu           getParametrosensayosidu()                                 Returns the current record's "Parametrosensayosidu" value
 * @method Parametrosensayosodu           getParametrosensayosodu()                                 Returns the current record's "Parametrosensayosodu" value
 * @method Doctrine_Collection            getModelos()                                              Returns the current record's "Modelos" collection
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposId()                     Sets the current record's "caracteristicastecnicasequipos_id" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposVersion()                Sets the current record's "caracteristicastecnicasequipos_version" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion1()           Sets the current record's "caracteristicastecnicasequipos_descripcion1" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion2()           Sets the current record's "caracteristicastecnicasequipos_descripcion2" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion3()           Sets the current record's "caracteristicastecnicasequipos_descripcion3" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion4()           Sets the current record's "caracteristicastecnicasequipos_descripcion4" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion5()           Sets the current record's "caracteristicastecnicasequipos_descripcion5" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposDescripcion6()           Sets the current record's "caracteristicastecnicasequipos_descripcion6" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposTensionnominal()         Sets the current record's "caracteristicastecnicasequipos_tensionnominal" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposFrecuencia()             Sets the current record's "caracteristicastecnicasequipos_frecuencia" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposPotenciamaxima()         Sets the current record's "caracteristicastecnicasequipos_potenciamaxima" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCorrientemaxima()        Sets the current record's "caracteristicastecnicasequipos_corrientemaxima" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCarga()                  Sets the current record's "caracteristicastecnicasequipos_carga" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposPresion()                Sets the current record's "caracteristicastecnicasequipos_presion" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCapacidadfrio()          Sets the current record's "caracteristicastecnicasequipos_capacidadfrio" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposPotencianominalfrio()    Sets the current record's "caracteristicastecnicasequipos_potencianominalfrio" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCorrientenominalfrio()   Sets the current record's "caracteristicastecnicasequipos_corrientenominalfrio" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposPeso()                   Sets the current record's "caracteristicastecnicasequipos_peso" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCapacidadcalor()         Sets the current record's "caracteristicastecnicasequipos_capacidadcalor" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposPotencianominalcalor()   Sets the current record's "caracteristicastecnicasequipos_potencianominalcalor" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposCorrientenominalcalor()  Sets the current record's "caracteristicastecnicasequipos_corrientenominalcalor" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposErr()                    Sets the current record's "caracteristicastecnicasequipos_err" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposEsidu()                  Sets the current record's "caracteristicastecnicasequipos_esidu" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposNombre()                 Sets the current record's "caracteristicastecnicasequipos_nombre" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposIdparametros()           Sets the current record's "caracteristicastecnicasequipos_idparametros" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposIdparametrosIdu()        Sets the current record's "caracteristicastecnicasequipos_idparametros_idu" value
 * @method Caracteristicastecnicasequipos setCaracteristicastecnicasequiposIdparametrosOdu()        Sets the current record's "caracteristicastecnicasequipos_idparametros_odu" value
 * @method Caracteristicastecnicasequipos setEsActivo()                                             Sets the current record's "es_activo" value
 * @method Caracteristicastecnicasequipos setId()                                                   Sets the current record's "id" value
 * @method Caracteristicastecnicasequipos setParametrosensayosidu()                                 Sets the current record's "Parametrosensayosidu" value
 * @method Caracteristicastecnicasequipos setParametrosensayosodu()                                 Sets the current record's "Parametrosensayosodu" value
 * @method Caracteristicastecnicasequipos setModelos()                                              Sets the current record's "Modelos" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCaracteristicastecnicasequipos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caracteristicastecnicasequipos');
        $this->hasColumn('caracteristicastecnicasequipos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_version', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion3', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion4', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion5', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_descripcion6', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_tensionnominal', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_frecuencia', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_potenciamaxima', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_corrientemaxima', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_carga', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_presion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_capacidadfrio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_potencianominalfrio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_corrientenominalfrio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_peso', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_capacidadcalor', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_potencianominalcalor', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_corrientenominalcalor', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_err', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_esidu', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_idparametros', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_idparametros_idu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caracteristicastecnicasequipos_idparametros_odu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('es_activo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parametrosensayosidu', array(
             'local' => 'caracteristicastecnicasequipos_idparametros_idu',
             'foreign' => 'parametrosensayosidu_id'));

        $this->hasOne('Parametrosensayosodu', array(
             'local' => 'caracteristicastecnicasequipos_idparametros_odu',
             'foreign' => 'parametrosensayosodu_id'));

        $this->hasMany('Modelos', array(
             'local' => 'caracteristicastecnicasequipos_nombre',
             'foreign' => 'modelos_referencia'));
    }
}