<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Fallasidu', 'doctrine');

/**
 * BaseFallasidu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $numerodefalla
 * @property string $descripcion
 * @property integer $prioridadalta
 * 
 * @method integer   getNumerodefalla() Returns the current record's "numerodefalla" value
 * @method string    getDescripcion()   Returns the current record's "descripcion" value
 * @method integer   getPrioridadalta() Returns the current record's "prioridadalta" value
 * @method Fallasidu setNumerodefalla() Sets the current record's "numerodefalla" value
 * @method Fallasidu setDescripcion()   Sets the current record's "descripcion" value
 * @method Fallasidu setPrioridadalta() Sets the current record's "prioridadalta" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFallasidu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fallasidu');
        $this->hasColumn('numerodefalla', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('prioridadalta', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}