<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ensayosrealizadosodu', 'doctrine');

/**
 * BaseEnsayosrealizadosodu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ensayosrealizadosodu_id
 * @property string $ensayosrealizadosodu_marca
 * @property string $ensayosrealizadosodu_modelo
 * @property string $ensayosrealizadosodu_codigo
 * @property string $ensayosrealizadosodu_serie
 * @property timestamp $ensayosrealizadosodu_fecha
 * @property integer $ensayosrealizadosodu_aprobado
 * @property string $ensayosrealizadosodu_dcf
 * @property float $ensayosrealizadosodu_diferenciadetemperatura
 * @property float $ensayosrealizadosodu_temperaturaambiente
 * @property float $ensayosrealizadosodu_humedad
 * @property float $ensayosrealizadosodu_tensionalta
 * @property float $ensayosrealizadosodu_tensionbaja
 * @property float $ensayosrealizadosodu_corrientealta
 * @property float $ensayosrealizadosodu_corrientebaja
 * @property float $ensayosrealizadosodu_potenciaalta
 * @property float $ensayosrealizadosodu_factordepotencia
 * @property float $ensayosrealizadosodu_velocidadalta
 * @property float $ensayosrealizadosodu_velocidadbaja
 * @property float $ensayosrealizadosodu_presioninicial
 * @property float $ensayosrealizadosodu_presionbajatension
 * @property float $ensayosrealizadosodu_presionensayo
 * @property float $ensayosrealizadosodu_presionrecuperacion
 * @property float $ensayosrealizadosodu_flags
 * @property float $ensayosrealizadosodu_tensionaltacalor
 * @property float $ensayosrealizadosodu_corrientealtacalor
 * @property float $ensayosrealizadosodu_factordepotenciacalor
 * @property float $ensayosrealizadosodu_potenciaaltacalor
 * @property float $ensayosrealizadosodu_velocidadaltacalor
 * @property float $ensayosrealizadosodu_temperaturaaltacalor
 * @property float $ensayosrealizadosodu_temperaturaambientecalor
 * @property float $ensayosrealizadosodu_humedadcalor
 * @property float $ensayosrealizadosodu_presionbajatensioncalor
 * @property string $ensayosrealizadosodu_vacio
 * @property string $ensayosrealizadosodu_hipot
 * @property string $ensayosrealizadosodu_fuga
 * @property string $ensayosrealizadosodu_observaciones
 * @property integer $ensayosrealizadosodu_tiempoensayo
 * @property integer $ensayosrealizadosodu_cantidadreimpresion
 * @property string $ensayosrealizadosodu_usuario
 * @property string $orden_fabricacion
 * 
 * @method integer              getEnsayosrealizadosoduId()                        Returns the current record's "ensayosrealizadosodu_id" value
 * @method string               getEnsayosrealizadosoduMarca()                     Returns the current record's "ensayosrealizadosodu_marca" value
 * @method string               getEnsayosrealizadosoduModelo()                    Returns the current record's "ensayosrealizadosodu_modelo" value
 * @method string               getEnsayosrealizadosoduCodigo()                    Returns the current record's "ensayosrealizadosodu_codigo" value
 * @method string               getEnsayosrealizadosoduSerie()                     Returns the current record's "ensayosrealizadosodu_serie" value
 * @method timestamp            getEnsayosrealizadosoduFecha()                     Returns the current record's "ensayosrealizadosodu_fecha" value
 * @method integer              getEnsayosrealizadosoduAprobado()                  Returns the current record's "ensayosrealizadosodu_aprobado" value
 * @method string               getEnsayosrealizadosoduDcf()                       Returns the current record's "ensayosrealizadosodu_dcf" value
 * @method float                getEnsayosrealizadosoduDiferenciadetemperatura()   Returns the current record's "ensayosrealizadosodu_diferenciadetemperatura" value
 * @method float                getEnsayosrealizadosoduTemperaturaambiente()       Returns the current record's "ensayosrealizadosodu_temperaturaambiente" value
 * @method float                getEnsayosrealizadosoduHumedad()                   Returns the current record's "ensayosrealizadosodu_humedad" value
 * @method float                getEnsayosrealizadosoduTensionalta()               Returns the current record's "ensayosrealizadosodu_tensionalta" value
 * @method float                getEnsayosrealizadosoduTensionbaja()               Returns the current record's "ensayosrealizadosodu_tensionbaja" value
 * @method float                getEnsayosrealizadosoduCorrientealta()             Returns the current record's "ensayosrealizadosodu_corrientealta" value
 * @method float                getEnsayosrealizadosoduCorrientebaja()             Returns the current record's "ensayosrealizadosodu_corrientebaja" value
 * @method float                getEnsayosrealizadosoduPotenciaalta()              Returns the current record's "ensayosrealizadosodu_potenciaalta" value
 * @method float                getEnsayosrealizadosoduFactordepotencia()          Returns the current record's "ensayosrealizadosodu_factordepotencia" value
 * @method float                getEnsayosrealizadosoduVelocidadalta()             Returns the current record's "ensayosrealizadosodu_velocidadalta" value
 * @method float                getEnsayosrealizadosoduVelocidadbaja()             Returns the current record's "ensayosrealizadosodu_velocidadbaja" value
 * @method float                getEnsayosrealizadosoduPresioninicial()            Returns the current record's "ensayosrealizadosodu_presioninicial" value
 * @method float                getEnsayosrealizadosoduPresionbajatension()        Returns the current record's "ensayosrealizadosodu_presionbajatension" value
 * @method float                getEnsayosrealizadosoduPresionensayo()             Returns the current record's "ensayosrealizadosodu_presionensayo" value
 * @method float                getEnsayosrealizadosoduPresionrecuperacion()       Returns the current record's "ensayosrealizadosodu_presionrecuperacion" value
 * @method float                getEnsayosrealizadosoduFlags()                     Returns the current record's "ensayosrealizadosodu_flags" value
 * @method float                getEnsayosrealizadosoduTensionaltacalor()          Returns the current record's "ensayosrealizadosodu_tensionaltacalor" value
 * @method float                getEnsayosrealizadosoduCorrientealtacalor()        Returns the current record's "ensayosrealizadosodu_corrientealtacalor" value
 * @method float                getEnsayosrealizadosoduFactordepotenciacalor()     Returns the current record's "ensayosrealizadosodu_factordepotenciacalor" value
 * @method float                getEnsayosrealizadosoduPotenciaaltacalor()         Returns the current record's "ensayosrealizadosodu_potenciaaltacalor" value
 * @method float                getEnsayosrealizadosoduVelocidadaltacalor()        Returns the current record's "ensayosrealizadosodu_velocidadaltacalor" value
 * @method float                getEnsayosrealizadosoduTemperaturaaltacalor()      Returns the current record's "ensayosrealizadosodu_temperaturaaltacalor" value
 * @method float                getEnsayosrealizadosoduTemperaturaambientecalor()  Returns the current record's "ensayosrealizadosodu_temperaturaambientecalor" value
 * @method float                getEnsayosrealizadosoduHumedadcalor()              Returns the current record's "ensayosrealizadosodu_humedadcalor" value
 * @method float                getEnsayosrealizadosoduPresionbajatensioncalor()   Returns the current record's "ensayosrealizadosodu_presionbajatensioncalor" value
 * @method string               getEnsayosrealizadosoduVacio()                     Returns the current record's "ensayosrealizadosodu_vacio" value
 * @method string               getEnsayosrealizadosoduHipot()                     Returns the current record's "ensayosrealizadosodu_hipot" value
 * @method string               getEnsayosrealizadosoduFuga()                      Returns the current record's "ensayosrealizadosodu_fuga" value
 * @method string               getEnsayosrealizadosoduObservaciones()             Returns the current record's "ensayosrealizadosodu_observaciones" value
 * @method integer              getEnsayosrealizadosoduTiempoensayo()              Returns the current record's "ensayosrealizadosodu_tiempoensayo" value
 * @method integer              getEnsayosrealizadosoduCantidadreimpresion()       Returns the current record's "ensayosrealizadosodu_cantidadreimpresion" value
 * @method string               getEnsayosrealizadosoduUsuario()                   Returns the current record's "ensayosrealizadosodu_usuario" value
 * @method string               getOrdenFabricacion()                              Returns the current record's "orden_fabricacion" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduId()                        Sets the current record's "ensayosrealizadosodu_id" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduMarca()                     Sets the current record's "ensayosrealizadosodu_marca" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduModelo()                    Sets the current record's "ensayosrealizadosodu_modelo" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduCodigo()                    Sets the current record's "ensayosrealizadosodu_codigo" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduSerie()                     Sets the current record's "ensayosrealizadosodu_serie" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduFecha()                     Sets the current record's "ensayosrealizadosodu_fecha" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduAprobado()                  Sets the current record's "ensayosrealizadosodu_aprobado" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduDcf()                       Sets the current record's "ensayosrealizadosodu_dcf" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduDiferenciadetemperatura()   Sets the current record's "ensayosrealizadosodu_diferenciadetemperatura" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTemperaturaambiente()       Sets the current record's "ensayosrealizadosodu_temperaturaambiente" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduHumedad()                   Sets the current record's "ensayosrealizadosodu_humedad" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTensionalta()               Sets the current record's "ensayosrealizadosodu_tensionalta" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTensionbaja()               Sets the current record's "ensayosrealizadosodu_tensionbaja" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduCorrientealta()             Sets the current record's "ensayosrealizadosodu_corrientealta" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduCorrientebaja()             Sets the current record's "ensayosrealizadosodu_corrientebaja" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPotenciaalta()              Sets the current record's "ensayosrealizadosodu_potenciaalta" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduFactordepotencia()          Sets the current record's "ensayosrealizadosodu_factordepotencia" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduVelocidadalta()             Sets the current record's "ensayosrealizadosodu_velocidadalta" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduVelocidadbaja()             Sets the current record's "ensayosrealizadosodu_velocidadbaja" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPresioninicial()            Sets the current record's "ensayosrealizadosodu_presioninicial" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPresionbajatension()        Sets the current record's "ensayosrealizadosodu_presionbajatension" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPresionensayo()             Sets the current record's "ensayosrealizadosodu_presionensayo" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPresionrecuperacion()       Sets the current record's "ensayosrealizadosodu_presionrecuperacion" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduFlags()                     Sets the current record's "ensayosrealizadosodu_flags" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTensionaltacalor()          Sets the current record's "ensayosrealizadosodu_tensionaltacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduCorrientealtacalor()        Sets the current record's "ensayosrealizadosodu_corrientealtacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduFactordepotenciacalor()     Sets the current record's "ensayosrealizadosodu_factordepotenciacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPotenciaaltacalor()         Sets the current record's "ensayosrealizadosodu_potenciaaltacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduVelocidadaltacalor()        Sets the current record's "ensayosrealizadosodu_velocidadaltacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTemperaturaaltacalor()      Sets the current record's "ensayosrealizadosodu_temperaturaaltacalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTemperaturaambientecalor()  Sets the current record's "ensayosrealizadosodu_temperaturaambientecalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduHumedadcalor()              Sets the current record's "ensayosrealizadosodu_humedadcalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduPresionbajatensioncalor()   Sets the current record's "ensayosrealizadosodu_presionbajatensioncalor" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduVacio()                     Sets the current record's "ensayosrealizadosodu_vacio" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduHipot()                     Sets the current record's "ensayosrealizadosodu_hipot" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduFuga()                      Sets the current record's "ensayosrealizadosodu_fuga" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduObservaciones()             Sets the current record's "ensayosrealizadosodu_observaciones" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduTiempoensayo()              Sets the current record's "ensayosrealizadosodu_tiempoensayo" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduCantidadreimpresion()       Sets the current record's "ensayosrealizadosodu_cantidadreimpresion" value
 * @method Ensayosrealizadosodu setEnsayosrealizadosoduUsuario()                   Sets the current record's "ensayosrealizadosodu_usuario" value
 * @method Ensayosrealizadosodu setOrdenFabricacion()                              Sets the current record's "orden_fabricacion" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnsayosrealizadosodu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ensayosrealizadosodu');
        $this->hasColumn('ensayosrealizadosodu_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ensayosrealizadosodu_marca', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_modelo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_codigo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_serie', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ensayosrealizadosodu_aprobado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ensayosrealizadosodu_dcf', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('ensayosrealizadosodu_diferenciadetemperatura', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_temperaturaambiente', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_humedad', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_tensionalta', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_tensionbaja', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_corrientealta', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_corrientebaja', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_potenciaalta', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_factordepotencia', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_velocidadalta', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_velocidadbaja', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_presioninicial', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_presionbajatension', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_presionensayo', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_presionrecuperacion', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_flags', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_tensionaltacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_corrientealtacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_factordepotenciacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_potenciaaltacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_velocidadaltacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_temperaturaaltacalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_temperaturaambientecalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_humedadcalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_presionbajatensioncalor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayosrealizadosodu_vacio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_hipot', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_fuga', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_observaciones', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ensayosrealizadosodu_tiempoensayo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ensayosrealizadosodu_cantidadreimpresion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ensayosrealizadosodu_usuario', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('orden_fabricacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'N/D',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}