<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parametrosensayosidu', 'doctrine');

/**
 * BaseParametrosensayosidu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parametrosensayosidu_id
 * @property string $parametrosensayosidu_referencia
 * @property string $parametrosensayosidu_descripcion
 * @property integer $parametrosensayosidu_dcfs
 * @property timestamp $parametrosensayosidu_modificado
 * @property integer $parametrosensayosidu_retardostopinicial
 * @property integer $parametrosensayosidu_retardostartmitad
 * @property integer $parametrosensayosidu_timeoutcalor
 * @property integer $parametrosensayosidu_timeoutfrio
 * @property integer $parametrosensayosidu_retardostart2bajatension
 * @property integer $parametrosensayosidu_tiempomodovelocidadbaja
 * @property integer $parametrosensayosidu_tiempomodovelocidadalta
 * @property integer $parametrosensayosidu_retardodesenergizado
 * @property integer $parametrosensayosidu_final
 * @property integer $parametrosensayosidu_temperatura
 * @property integer $parametrosensayosidu_velocidadbajatensionmin
 * @property integer $parametrosensayosidu_velocidadbajatensionmax
 * @property integer $parametrosensayosidu_corrientebajatensionmin
 * @property integer $parametrosensayosidu_corrientebajatensionmax
 * @property integer $parametrosensayosidu_velocidadminmodovelbaja
 * @property integer $parametrosensayosidu_velocidadmaxmodovelbaja
 * @property integer $parametrosensayosidu_corrienteminmodovelbaja
 * @property integer $parametrosensayosidu_corrientemaxmodovelbaja
 * @property integer $parametrosensayosidu_velocidadminmodovelalta
 * @property integer $parametrosensayosidu_velocidadmaxmodovelalta
 * @property integer $parametrosensayosidu_corrienteminmodovelalta
 * @property integer $parametrosensayosidu_corrientemaxmodovelalta
 * @property integer $parametrosensayosidu_timeoutbajatension
 * @property integer $parametrosensayosidu_idversion
 * @property integer $es_activo
 * @property Versiones $Versiones
 * @property Doctrine_Collection $Caracteristicastecnicasequipos
 * 
 * @method integer              getParametrosensayosiduId()                        Returns the current record's "parametrosensayosidu_id" value
 * @method string               getParametrosensayosiduReferencia()                Returns the current record's "parametrosensayosidu_referencia" value
 * @method string               getParametrosensayosiduDescripcion()               Returns the current record's "parametrosensayosidu_descripcion" value
 * @method integer              getParametrosensayosiduDcfs()                      Returns the current record's "parametrosensayosidu_dcfs" value
 * @method timestamp            getParametrosensayosiduModificado()                Returns the current record's "parametrosensayosidu_modificado" value
 * @method integer              getParametrosensayosiduRetardostopinicial()        Returns the current record's "parametrosensayosidu_retardostopinicial" value
 * @method integer              getParametrosensayosiduRetardostartmitad()         Returns the current record's "parametrosensayosidu_retardostartmitad" value
 * @method integer              getParametrosensayosiduTimeoutcalor()              Returns the current record's "parametrosensayosidu_timeoutcalor" value
 * @method integer              getParametrosensayosiduTimeoutfrio()               Returns the current record's "parametrosensayosidu_timeoutfrio" value
 * @method integer              getParametrosensayosiduRetardostart2bajatension()  Returns the current record's "parametrosensayosidu_retardostart2bajatension" value
 * @method integer              getParametrosensayosiduTiempomodovelocidadbaja()   Returns the current record's "parametrosensayosidu_tiempomodovelocidadbaja" value
 * @method integer              getParametrosensayosiduTiempomodovelocidadalta()   Returns the current record's "parametrosensayosidu_tiempomodovelocidadalta" value
 * @method integer              getParametrosensayosiduRetardodesenergizado()      Returns the current record's "parametrosensayosidu_retardodesenergizado" value
 * @method integer              getParametrosensayosiduFinal()                     Returns the current record's "parametrosensayosidu_final" value
 * @method integer              getParametrosensayosiduTemperatura()               Returns the current record's "parametrosensayosidu_temperatura" value
 * @method integer              getParametrosensayosiduVelocidadbajatensionmin()   Returns the current record's "parametrosensayosidu_velocidadbajatensionmin" value
 * @method integer              getParametrosensayosiduVelocidadbajatensionmax()   Returns the current record's "parametrosensayosidu_velocidadbajatensionmax" value
 * @method integer              getParametrosensayosiduCorrientebajatensionmin()   Returns the current record's "parametrosensayosidu_corrientebajatensionmin" value
 * @method integer              getParametrosensayosiduCorrientebajatensionmax()   Returns the current record's "parametrosensayosidu_corrientebajatensionmax" value
 * @method integer              getParametrosensayosiduVelocidadminmodovelbaja()   Returns the current record's "parametrosensayosidu_velocidadminmodovelbaja" value
 * @method integer              getParametrosensayosiduVelocidadmaxmodovelbaja()   Returns the current record's "parametrosensayosidu_velocidadmaxmodovelbaja" value
 * @method integer              getParametrosensayosiduCorrienteminmodovelbaja()   Returns the current record's "parametrosensayosidu_corrienteminmodovelbaja" value
 * @method integer              getParametrosensayosiduCorrientemaxmodovelbaja()   Returns the current record's "parametrosensayosidu_corrientemaxmodovelbaja" value
 * @method integer              getParametrosensayosiduVelocidadminmodovelalta()   Returns the current record's "parametrosensayosidu_velocidadminmodovelalta" value
 * @method integer              getParametrosensayosiduVelocidadmaxmodovelalta()   Returns the current record's "parametrosensayosidu_velocidadmaxmodovelalta" value
 * @method integer              getParametrosensayosiduCorrienteminmodovelalta()   Returns the current record's "parametrosensayosidu_corrienteminmodovelalta" value
 * @method integer              getParametrosensayosiduCorrientemaxmodovelalta()   Returns the current record's "parametrosensayosidu_corrientemaxmodovelalta" value
 * @method integer              getParametrosensayosiduTimeoutbajatension()        Returns the current record's "parametrosensayosidu_timeoutbajatension" value
 * @method integer              getParametrosensayosiduIdversion()                 Returns the current record's "parametrosensayosidu_idversion" value
 * @method integer              getEsActivo()                                      Returns the current record's "es_activo" value
 * @method Versiones            getVersiones()                                     Returns the current record's "Versiones" value
 * @method Doctrine_Collection  getCaracteristicastecnicasequipos()                Returns the current record's "Caracteristicastecnicasequipos" collection
 * @method Parametrosensayosidu setParametrosensayosiduId()                        Sets the current record's "parametrosensayosidu_id" value
 * @method Parametrosensayosidu setParametrosensayosiduReferencia()                Sets the current record's "parametrosensayosidu_referencia" value
 * @method Parametrosensayosidu setParametrosensayosiduDescripcion()               Sets the current record's "parametrosensayosidu_descripcion" value
 * @method Parametrosensayosidu setParametrosensayosiduDcfs()                      Sets the current record's "parametrosensayosidu_dcfs" value
 * @method Parametrosensayosidu setParametrosensayosiduModificado()                Sets the current record's "parametrosensayosidu_modificado" value
 * @method Parametrosensayosidu setParametrosensayosiduRetardostopinicial()        Sets the current record's "parametrosensayosidu_retardostopinicial" value
 * @method Parametrosensayosidu setParametrosensayosiduRetardostartmitad()         Sets the current record's "parametrosensayosidu_retardostartmitad" value
 * @method Parametrosensayosidu setParametrosensayosiduTimeoutcalor()              Sets the current record's "parametrosensayosidu_timeoutcalor" value
 * @method Parametrosensayosidu setParametrosensayosiduTimeoutfrio()               Sets the current record's "parametrosensayosidu_timeoutfrio" value
 * @method Parametrosensayosidu setParametrosensayosiduRetardostart2bajatension()  Sets the current record's "parametrosensayosidu_retardostart2bajatension" value
 * @method Parametrosensayosidu setParametrosensayosiduTiempomodovelocidadbaja()   Sets the current record's "parametrosensayosidu_tiempomodovelocidadbaja" value
 * @method Parametrosensayosidu setParametrosensayosiduTiempomodovelocidadalta()   Sets the current record's "parametrosensayosidu_tiempomodovelocidadalta" value
 * @method Parametrosensayosidu setParametrosensayosiduRetardodesenergizado()      Sets the current record's "parametrosensayosidu_retardodesenergizado" value
 * @method Parametrosensayosidu setParametrosensayosiduFinal()                     Sets the current record's "parametrosensayosidu_final" value
 * @method Parametrosensayosidu setParametrosensayosiduTemperatura()               Sets the current record's "parametrosensayosidu_temperatura" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadbajatensionmin()   Sets the current record's "parametrosensayosidu_velocidadbajatensionmin" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadbajatensionmax()   Sets the current record's "parametrosensayosidu_velocidadbajatensionmax" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrientebajatensionmin()   Sets the current record's "parametrosensayosidu_corrientebajatensionmin" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrientebajatensionmax()   Sets the current record's "parametrosensayosidu_corrientebajatensionmax" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadminmodovelbaja()   Sets the current record's "parametrosensayosidu_velocidadminmodovelbaja" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadmaxmodovelbaja()   Sets the current record's "parametrosensayosidu_velocidadmaxmodovelbaja" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrienteminmodovelbaja()   Sets the current record's "parametrosensayosidu_corrienteminmodovelbaja" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrientemaxmodovelbaja()   Sets the current record's "parametrosensayosidu_corrientemaxmodovelbaja" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadminmodovelalta()   Sets the current record's "parametrosensayosidu_velocidadminmodovelalta" value
 * @method Parametrosensayosidu setParametrosensayosiduVelocidadmaxmodovelalta()   Sets the current record's "parametrosensayosidu_velocidadmaxmodovelalta" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrienteminmodovelalta()   Sets the current record's "parametrosensayosidu_corrienteminmodovelalta" value
 * @method Parametrosensayosidu setParametrosensayosiduCorrientemaxmodovelalta()   Sets the current record's "parametrosensayosidu_corrientemaxmodovelalta" value
 * @method Parametrosensayosidu setParametrosensayosiduTimeoutbajatension()        Sets the current record's "parametrosensayosidu_timeoutbajatension" value
 * @method Parametrosensayosidu setParametrosensayosiduIdversion()                 Sets the current record's "parametrosensayosidu_idversion" value
 * @method Parametrosensayosidu setEsActivo()                                      Sets the current record's "es_activo" value
 * @method Parametrosensayosidu setVersiones()                                     Sets the current record's "Versiones" value
 * @method Parametrosensayosidu setCaracteristicastecnicasequipos()                Sets the current record's "Caracteristicastecnicasequipos" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametrosensayosidu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametrosensayosidu');
        $this->hasColumn('parametrosensayosidu_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_referencia', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('parametrosensayosidu_descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('parametrosensayosidu_dcfs', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_modificado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('parametrosensayosidu_retardostopinicial', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_retardostartmitad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_timeoutcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_timeoutfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_retardostart2bajatension', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_tiempomodovelocidadbaja', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_tiempomodovelocidadalta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_retardodesenergizado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_final', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_temperatura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadbajatensionmin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadbajatensionmax', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrientebajatensionmin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrientebajatensionmax', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadminmodovelbaja', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadmaxmodovelbaja', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrienteminmodovelbaja', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrientemaxmodovelbaja', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadminmodovelalta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_velocidadmaxmodovelalta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrienteminmodovelalta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_corrientemaxmodovelalta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_timeoutbajatension', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosidu_idversion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('es_activo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Versiones', array(
             'local' => 'parametrosensayosidu_idversion',
             'foreign' => 'versiones_id'));

        $this->hasMany('Caracteristicastecnicasequipos', array(
             'local' => 'parametrosensayosidu_id',
             'foreign' => 'caracteristicastecnicasequipos_idparametros_idu'));
    }
}