<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Serie', 'doctrine');

/**
 * BaseSerie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $serie_id
 * @property string $serie_tipo
 * @property integer $serie_numero
 * @property integer $serie_maximo
 * @property integer $serie_minimo
 * @property string $serie_prefijo
 * @property integer $serie_sufijo
 * 
 * @method integer getSerieId()       Returns the current record's "serie_id" value
 * @method string  getSerieTipo()     Returns the current record's "serie_tipo" value
 * @method integer getSerieNumero()   Returns the current record's "serie_numero" value
 * @method integer getSerieMaximo()   Returns the current record's "serie_maximo" value
 * @method integer getSerieMinimo()   Returns the current record's "serie_minimo" value
 * @method string  getSeriePrefijo()  Returns the current record's "serie_prefijo" value
 * @method integer getSerieSufijo()   Returns the current record's "serie_sufijo" value
 * @method Serie   setSerieId()       Sets the current record's "serie_id" value
 * @method Serie   setSerieTipo()     Sets the current record's "serie_tipo" value
 * @method Serie   setSerieNumero()   Sets the current record's "serie_numero" value
 * @method Serie   setSerieMaximo()   Sets the current record's "serie_maximo" value
 * @method Serie   setSerieMinimo()   Sets the current record's "serie_minimo" value
 * @method Serie   setSeriePrefijo()  Sets the current record's "serie_prefijo" value
 * @method Serie   setSerieSufijo()   Sets the current record's "serie_sufijo" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSerie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('serie');
        $this->hasColumn('serie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('serie_tipo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('serie_numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('serie_maximo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('serie_minimo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('serie_prefijo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('serie_sufijo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}