<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Infoensayosreset', 'doctrine');

/**
 * BaseInfoensayosreset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha
 * @property integer $numeroensayosok
 * @property string $usuario
 * @property string $pc
 * @property bit $esidu
 * 
 * @method integer          getId()              Returns the current record's "id" value
 * @method timestamp        getFecha()           Returns the current record's "fecha" value
 * @method integer          getNumeroensayosok() Returns the current record's "numeroensayosok" value
 * @method string           getUsuario()         Returns the current record's "usuario" value
 * @method string           getPc()              Returns the current record's "pc" value
 * @method bit              getEsidu()           Returns the current record's "esidu" value
 * @method Infoensayosreset setId()              Sets the current record's "id" value
 * @method Infoensayosreset setFecha()           Sets the current record's "fecha" value
 * @method Infoensayosreset setNumeroensayosok() Sets the current record's "numeroensayosok" value
 * @method Infoensayosreset setUsuario()         Sets the current record's "usuario" value
 * @method Infoensayosreset setPc()              Sets the current record's "pc" value
 * @method Infoensayosreset setEsidu()           Sets the current record's "esidu" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfoensayosreset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('infoensayosreset');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('numeroensayosok', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'USER',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('pc', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"PC"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('esidu', 'bit', 1, array(
             'type' => 'bit',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'b\'0\'',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}