<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Componentesetiquetas', 'doctrine');

/**
 * BaseComponentesetiquetas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $componentesetiquetas_id
 * @property string $componentesetiquetas_font
 * @property float $componentesetiquetas_size
 * @property integer $componentesetiquetas_bold
 * @property integer $componentesetiquetas_italic
 * @property float $componentesetiquetas_yinicial
 * @property float $componentesetiquetas_xinicial
 * @property float $componentesetiquetas_yfinal
 * @property integer $componentesetiquetas_variable
 * @property integer $componentesetiquetas_tipo
 * @property integer $componentesetiquetas_alignh
 * @property integer $componentesetiquetas_alignv
 * @property float $componentesetiquetas_xfinal
 * @property string $componentesetiquetas_param
 * @property integer $componentesetiquetas_numeroetiqueta
 * 
 * @method integer              getComponentesetiquetasId()              Returns the current record's "componentesetiquetas_id" value
 * @method string               getComponentesetiquetasFont()            Returns the current record's "componentesetiquetas_font" value
 * @method float                getComponentesetiquetasSize()            Returns the current record's "componentesetiquetas_size" value
 * @method integer              getComponentesetiquetasBold()            Returns the current record's "componentesetiquetas_bold" value
 * @method integer              getComponentesetiquetasItalic()          Returns the current record's "componentesetiquetas_italic" value
 * @method float                getComponentesetiquetasYinicial()        Returns the current record's "componentesetiquetas_yinicial" value
 * @method float                getComponentesetiquetasXinicial()        Returns the current record's "componentesetiquetas_xinicial" value
 * @method float                getComponentesetiquetasYfinal()          Returns the current record's "componentesetiquetas_yfinal" value
 * @method integer              getComponentesetiquetasVariable()        Returns the current record's "componentesetiquetas_variable" value
 * @method integer              getComponentesetiquetasTipo()            Returns the current record's "componentesetiquetas_tipo" value
 * @method integer              getComponentesetiquetasAlignh()          Returns the current record's "componentesetiquetas_alignh" value
 * @method integer              getComponentesetiquetasAlignv()          Returns the current record's "componentesetiquetas_alignv" value
 * @method float                getComponentesetiquetasXfinal()          Returns the current record's "componentesetiquetas_xfinal" value
 * @method string               getComponentesetiquetasParam()           Returns the current record's "componentesetiquetas_param" value
 * @method integer              getComponentesetiquetasNumeroetiqueta()  Returns the current record's "componentesetiquetas_numeroetiqueta" value
 * @method Componentesetiquetas setComponentesetiquetasId()              Sets the current record's "componentesetiquetas_id" value
 * @method Componentesetiquetas setComponentesetiquetasFont()            Sets the current record's "componentesetiquetas_font" value
 * @method Componentesetiquetas setComponentesetiquetasSize()            Sets the current record's "componentesetiquetas_size" value
 * @method Componentesetiquetas setComponentesetiquetasBold()            Sets the current record's "componentesetiquetas_bold" value
 * @method Componentesetiquetas setComponentesetiquetasItalic()          Sets the current record's "componentesetiquetas_italic" value
 * @method Componentesetiquetas setComponentesetiquetasYinicial()        Sets the current record's "componentesetiquetas_yinicial" value
 * @method Componentesetiquetas setComponentesetiquetasXinicial()        Sets the current record's "componentesetiquetas_xinicial" value
 * @method Componentesetiquetas setComponentesetiquetasYfinal()          Sets the current record's "componentesetiquetas_yfinal" value
 * @method Componentesetiquetas setComponentesetiquetasVariable()        Sets the current record's "componentesetiquetas_variable" value
 * @method Componentesetiquetas setComponentesetiquetasTipo()            Sets the current record's "componentesetiquetas_tipo" value
 * @method Componentesetiquetas setComponentesetiquetasAlignh()          Sets the current record's "componentesetiquetas_alignh" value
 * @method Componentesetiquetas setComponentesetiquetasAlignv()          Sets the current record's "componentesetiquetas_alignv" value
 * @method Componentesetiquetas setComponentesetiquetasXfinal()          Sets the current record's "componentesetiquetas_xfinal" value
 * @method Componentesetiquetas setComponentesetiquetasParam()           Sets the current record's "componentesetiquetas_param" value
 * @method Componentesetiquetas setComponentesetiquetasNumeroetiqueta()  Sets the current record's "componentesetiquetas_numeroetiqueta" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponentesetiquetas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('componentesetiquetas');
        $this->hasColumn('componentesetiquetas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('componentesetiquetas_font', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'ARIAL',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('componentesetiquetas_size', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '12',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('componentesetiquetas_bold', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('componentesetiquetas_italic', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('componentesetiquetas_yinicial', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('componentesetiquetas_xinicial', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('componentesetiquetas_yfinal', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('componentesetiquetas_variable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('componentesetiquetas_tipo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('componentesetiquetas_alignh', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('componentesetiquetas_alignv', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('componentesetiquetas_xfinal', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('componentesetiquetas_param', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('componentesetiquetas_numeroetiqueta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}