<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parametrosensayosodu', 'doctrine');

/**
 * BaseParametrosensayosodu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parametrosensayosodu_id
 * @property string $parametrosensayosodu_ref
 * @property string $parametrosensayosodu_descripcion
 * @property timestamp $parametrosensayosodu_modificado
 * @property integer $parametrosensayosodu_dcfs
 * @property integer $parametrosensayosodu_tiempoinicialestabilizacion
 * @property integer $parametrosensayosodu_tiempomaximoestabilizacion
 * @property integer $parametrosensayosodu_tiempobajatension
 * @property integer $parametrosensayosodu_tiempomaximobajatension
 * @property integer $parametrosensayosodu_tiempomedicioncalor
 * @property integer $parametrosensayosodu_tiempomaximomedicioncalor
 * @property integer $parametrosensayosodu_tiempomedicionfrio
 * @property integer $parametrosensayosodu_tiemporecuperacionminima
 * @property integer $parametrosensayosodu_tiempomaximorecuperacionminima
 * @property integer $parametrosensayosodu_delayarranquecompresor
 * @property integer $parametrosensayosodu_tiempoapagadoentrecaloryfrio
 * @property integer $parametrosensayosodu_tiempocierrevalvula1
 * @property integer $parametrosensayosodu_tiempocierrevalvula2
 * @property integer $parametrosensayosodu_tiempofinal
 * @property integer $parametrosensayosodu_presioninicialmin
 * @property integer $parametrosensayosodu_presioninicialmax
 * @property integer $parametrosensayosodu_deltapresionestabilizacionmin
 * @property integer $parametrosensayosodu_deltapresionestabilizacionmax
 * @property integer $parametrosensayosodu_velocidadminbajatension
 * @property integer $parametrosensayosodu_deltapresionbajatensionmin
 * @property integer $parametrosensayosodu_deltapresionbajatensionmax
 * @property integer $parametrosensayosodu_deltatempmincalor
 * @property integer $parametrosensayosodu_deltatempmaxcalor
 * @property integer $parametrosensayosodu_corrientemincalor
 * @property integer $parametrosensayosodu_corrientemaxcalor
 * @property integer $parametrosensayosodu_potenciamincalor
 * @property integer $parametrosensayosodu_potenciamaxcalor
 * @property integer $parametrosensayosodu_velocidadmaxventiladorcalor
 * @property integer $parametrosensayosodu_velocidadminventiladorcalor
 * @property integer $parametrosensayosodu_presionminapagadocompresor
 * @property integer $parametrosensayosodu_deltatempminfrio
 * @property integer $parametrosensayosodu_deltatempmaxfrio
 * @property integer $parametrosensayosodu_corrientemaxfrio
 * @property integer $parametrosensayosodu_corrienteminfrio
 * @property integer $parametrosensayosodu_potenciaminfrio
 * @property integer $parametrosensayosodu_potenciamaxfrio
 * @property integer $parametrosensayosodu_velocidadminventiladorfrio
 * @property integer $parametrosensayosodu_velocidadmaxventiladorfrio
 * @property integer $parametrosensayosodu_presionminfrio
 * @property integer $parametrosensayosodu_presionmaxfrio
 * @property integer $parametrosensayosodu_presionmaxrecuperacion
 * @property integer $parametrosensayosodu_idversion
 * @property integer $es_activo
 * @property Versiones $Versiones
 * @property Doctrine_Collection $Caracteristicastecnicasequipos
 * 
 * @method integer              getParametrosensayosoduId()                              Returns the current record's "parametrosensayosodu_id" value
 * @method string               getParametrosensayosoduRef()                             Returns the current record's "parametrosensayosodu_ref" value
 * @method string               getParametrosensayosoduDescripcion()                     Returns the current record's "parametrosensayosodu_descripcion" value
 * @method timestamp            getParametrosensayosoduModificado()                      Returns the current record's "parametrosensayosodu_modificado" value
 * @method integer              getParametrosensayosoduDcfs()                            Returns the current record's "parametrosensayosodu_dcfs" value
 * @method integer              getParametrosensayosoduTiempoinicialestabilizacion()     Returns the current record's "parametrosensayosodu_tiempoinicialestabilizacion" value
 * @method integer              getParametrosensayosoduTiempomaximoestabilizacion()      Returns the current record's "parametrosensayosodu_tiempomaximoestabilizacion" value
 * @method integer              getParametrosensayosoduTiempobajatension()               Returns the current record's "parametrosensayosodu_tiempobajatension" value
 * @method integer              getParametrosensayosoduTiempomaximobajatension()         Returns the current record's "parametrosensayosodu_tiempomaximobajatension" value
 * @method integer              getParametrosensayosoduTiempomedicioncalor()             Returns the current record's "parametrosensayosodu_tiempomedicioncalor" value
 * @method integer              getParametrosensayosoduTiempomaximomedicioncalor()       Returns the current record's "parametrosensayosodu_tiempomaximomedicioncalor" value
 * @method integer              getParametrosensayosoduTiempomedicionfrio()              Returns the current record's "parametrosensayosodu_tiempomedicionfrio" value
 * @method integer              getParametrosensayosoduTiemporecuperacionminima()        Returns the current record's "parametrosensayosodu_tiemporecuperacionminima" value
 * @method integer              getParametrosensayosoduTiempomaximorecuperacionminima()  Returns the current record's "parametrosensayosodu_tiempomaximorecuperacionminima" value
 * @method integer              getParametrosensayosoduDelayarranquecompresor()          Returns the current record's "parametrosensayosodu_delayarranquecompresor" value
 * @method integer              getParametrosensayosoduTiempoapagadoentrecaloryfrio()    Returns the current record's "parametrosensayosodu_tiempoapagadoentrecaloryfrio" value
 * @method integer              getParametrosensayosoduTiempocierrevalvula1()            Returns the current record's "parametrosensayosodu_tiempocierrevalvula1" value
 * @method integer              getParametrosensayosoduTiempocierrevalvula2()            Returns the current record's "parametrosensayosodu_tiempocierrevalvula2" value
 * @method integer              getParametrosensayosoduTiempofinal()                     Returns the current record's "parametrosensayosodu_tiempofinal" value
 * @method integer              getParametrosensayosoduPresioninicialmin()               Returns the current record's "parametrosensayosodu_presioninicialmin" value
 * @method integer              getParametrosensayosoduPresioninicialmax()               Returns the current record's "parametrosensayosodu_presioninicialmax" value
 * @method integer              getParametrosensayosoduDeltapresionestabilizacionmin()   Returns the current record's "parametrosensayosodu_deltapresionestabilizacionmin" value
 * @method integer              getParametrosensayosoduDeltapresionestabilizacionmax()   Returns the current record's "parametrosensayosodu_deltapresionestabilizacionmax" value
 * @method integer              getParametrosensayosoduVelocidadminbajatension()         Returns the current record's "parametrosensayosodu_velocidadminbajatension" value
 * @method integer              getParametrosensayosoduDeltapresionbajatensionmin()      Returns the current record's "parametrosensayosodu_deltapresionbajatensionmin" value
 * @method integer              getParametrosensayosoduDeltapresionbajatensionmax()      Returns the current record's "parametrosensayosodu_deltapresionbajatensionmax" value
 * @method integer              getParametrosensayosoduDeltatempmincalor()               Returns the current record's "parametrosensayosodu_deltatempmincalor" value
 * @method integer              getParametrosensayosoduDeltatempmaxcalor()               Returns the current record's "parametrosensayosodu_deltatempmaxcalor" value
 * @method integer              getParametrosensayosoduCorrientemincalor()               Returns the current record's "parametrosensayosodu_corrientemincalor" value
 * @method integer              getParametrosensayosoduCorrientemaxcalor()               Returns the current record's "parametrosensayosodu_corrientemaxcalor" value
 * @method integer              getParametrosensayosoduPotenciamincalor()                Returns the current record's "parametrosensayosodu_potenciamincalor" value
 * @method integer              getParametrosensayosoduPotenciamaxcalor()                Returns the current record's "parametrosensayosodu_potenciamaxcalor" value
 * @method integer              getParametrosensayosoduVelocidadmaxventiladorcalor()     Returns the current record's "parametrosensayosodu_velocidadmaxventiladorcalor" value
 * @method integer              getParametrosensayosoduVelocidadminventiladorcalor()     Returns the current record's "parametrosensayosodu_velocidadminventiladorcalor" value
 * @method integer              getParametrosensayosoduPresionminapagadocompresor()      Returns the current record's "parametrosensayosodu_presionminapagadocompresor" value
 * @method integer              getParametrosensayosoduDeltatempminfrio()                Returns the current record's "parametrosensayosodu_deltatempminfrio" value
 * @method integer              getParametrosensayosoduDeltatempmaxfrio()                Returns the current record's "parametrosensayosodu_deltatempmaxfrio" value
 * @method integer              getParametrosensayosoduCorrientemaxfrio()                Returns the current record's "parametrosensayosodu_corrientemaxfrio" value
 * @method integer              getParametrosensayosoduCorrienteminfrio()                Returns the current record's "parametrosensayosodu_corrienteminfrio" value
 * @method integer              getParametrosensayosoduPotenciaminfrio()                 Returns the current record's "parametrosensayosodu_potenciaminfrio" value
 * @method integer              getParametrosensayosoduPotenciamaxfrio()                 Returns the current record's "parametrosensayosodu_potenciamaxfrio" value
 * @method integer              getParametrosensayosoduVelocidadminventiladorfrio()      Returns the current record's "parametrosensayosodu_velocidadminventiladorfrio" value
 * @method integer              getParametrosensayosoduVelocidadmaxventiladorfrio()      Returns the current record's "parametrosensayosodu_velocidadmaxventiladorfrio" value
 * @method integer              getParametrosensayosoduPresionminfrio()                  Returns the current record's "parametrosensayosodu_presionminfrio" value
 * @method integer              getParametrosensayosoduPresionmaxfrio()                  Returns the current record's "parametrosensayosodu_presionmaxfrio" value
 * @method integer              getParametrosensayosoduPresionmaxrecuperacion()          Returns the current record's "parametrosensayosodu_presionmaxrecuperacion" value
 * @method integer              getParametrosensayosoduIdversion()                       Returns the current record's "parametrosensayosodu_idversion" value
 * @method integer              getEsActivo()                                            Returns the current record's "es_activo" value
 * @method Versiones            getVersiones()                                           Returns the current record's "Versiones" value
 * @method Doctrine_Collection  getCaracteristicastecnicasequipos()                      Returns the current record's "Caracteristicastecnicasequipos" collection
 * @method Parametrosensayosodu setParametrosensayosoduId()                              Sets the current record's "parametrosensayosodu_id" value
 * @method Parametrosensayosodu setParametrosensayosoduRef()                             Sets the current record's "parametrosensayosodu_ref" value
 * @method Parametrosensayosodu setParametrosensayosoduDescripcion()                     Sets the current record's "parametrosensayosodu_descripcion" value
 * @method Parametrosensayosodu setParametrosensayosoduModificado()                      Sets the current record's "parametrosensayosodu_modificado" value
 * @method Parametrosensayosodu setParametrosensayosoduDcfs()                            Sets the current record's "parametrosensayosodu_dcfs" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempoinicialestabilizacion()     Sets the current record's "parametrosensayosodu_tiempoinicialestabilizacion" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomaximoestabilizacion()      Sets the current record's "parametrosensayosodu_tiempomaximoestabilizacion" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempobajatension()               Sets the current record's "parametrosensayosodu_tiempobajatension" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomaximobajatension()         Sets the current record's "parametrosensayosodu_tiempomaximobajatension" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomedicioncalor()             Sets the current record's "parametrosensayosodu_tiempomedicioncalor" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomaximomedicioncalor()       Sets the current record's "parametrosensayosodu_tiempomaximomedicioncalor" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomedicionfrio()              Sets the current record's "parametrosensayosodu_tiempomedicionfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduTiemporecuperacionminima()        Sets the current record's "parametrosensayosodu_tiemporecuperacionminima" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempomaximorecuperacionminima()  Sets the current record's "parametrosensayosodu_tiempomaximorecuperacionminima" value
 * @method Parametrosensayosodu setParametrosensayosoduDelayarranquecompresor()          Sets the current record's "parametrosensayosodu_delayarranquecompresor" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempoapagadoentrecaloryfrio()    Sets the current record's "parametrosensayosodu_tiempoapagadoentrecaloryfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempocierrevalvula1()            Sets the current record's "parametrosensayosodu_tiempocierrevalvula1" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempocierrevalvula2()            Sets the current record's "parametrosensayosodu_tiempocierrevalvula2" value
 * @method Parametrosensayosodu setParametrosensayosoduTiempofinal()                     Sets the current record's "parametrosensayosodu_tiempofinal" value
 * @method Parametrosensayosodu setParametrosensayosoduPresioninicialmin()               Sets the current record's "parametrosensayosodu_presioninicialmin" value
 * @method Parametrosensayosodu setParametrosensayosoduPresioninicialmax()               Sets the current record's "parametrosensayosodu_presioninicialmax" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltapresionestabilizacionmin()   Sets the current record's "parametrosensayosodu_deltapresionestabilizacionmin" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltapresionestabilizacionmax()   Sets the current record's "parametrosensayosodu_deltapresionestabilizacionmax" value
 * @method Parametrosensayosodu setParametrosensayosoduVelocidadminbajatension()         Sets the current record's "parametrosensayosodu_velocidadminbajatension" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltapresionbajatensionmin()      Sets the current record's "parametrosensayosodu_deltapresionbajatensionmin" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltapresionbajatensionmax()      Sets the current record's "parametrosensayosodu_deltapresionbajatensionmax" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltatempmincalor()               Sets the current record's "parametrosensayosodu_deltatempmincalor" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltatempmaxcalor()               Sets the current record's "parametrosensayosodu_deltatempmaxcalor" value
 * @method Parametrosensayosodu setParametrosensayosoduCorrientemincalor()               Sets the current record's "parametrosensayosodu_corrientemincalor" value
 * @method Parametrosensayosodu setParametrosensayosoduCorrientemaxcalor()               Sets the current record's "parametrosensayosodu_corrientemaxcalor" value
 * @method Parametrosensayosodu setParametrosensayosoduPotenciamincalor()                Sets the current record's "parametrosensayosodu_potenciamincalor" value
 * @method Parametrosensayosodu setParametrosensayosoduPotenciamaxcalor()                Sets the current record's "parametrosensayosodu_potenciamaxcalor" value
 * @method Parametrosensayosodu setParametrosensayosoduVelocidadmaxventiladorcalor()     Sets the current record's "parametrosensayosodu_velocidadmaxventiladorcalor" value
 * @method Parametrosensayosodu setParametrosensayosoduVelocidadminventiladorcalor()     Sets the current record's "parametrosensayosodu_velocidadminventiladorcalor" value
 * @method Parametrosensayosodu setParametrosensayosoduPresionminapagadocompresor()      Sets the current record's "parametrosensayosodu_presionminapagadocompresor" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltatempminfrio()                Sets the current record's "parametrosensayosodu_deltatempminfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduDeltatempmaxfrio()                Sets the current record's "parametrosensayosodu_deltatempmaxfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduCorrientemaxfrio()                Sets the current record's "parametrosensayosodu_corrientemaxfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduCorrienteminfrio()                Sets the current record's "parametrosensayosodu_corrienteminfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduPotenciaminfrio()                 Sets the current record's "parametrosensayosodu_potenciaminfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduPotenciamaxfrio()                 Sets the current record's "parametrosensayosodu_potenciamaxfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduVelocidadminventiladorfrio()      Sets the current record's "parametrosensayosodu_velocidadminventiladorfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduVelocidadmaxventiladorfrio()      Sets the current record's "parametrosensayosodu_velocidadmaxventiladorfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduPresionminfrio()                  Sets the current record's "parametrosensayosodu_presionminfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduPresionmaxfrio()                  Sets the current record's "parametrosensayosodu_presionmaxfrio" value
 * @method Parametrosensayosodu setParametrosensayosoduPresionmaxrecuperacion()          Sets the current record's "parametrosensayosodu_presionmaxrecuperacion" value
 * @method Parametrosensayosodu setParametrosensayosoduIdversion()                       Sets the current record's "parametrosensayosodu_idversion" value
 * @method Parametrosensayosodu setEsActivo()                                            Sets the current record's "es_activo" value
 * @method Parametrosensayosodu setVersiones()                                           Sets the current record's "Versiones" value
 * @method Parametrosensayosodu setCaracteristicastecnicasequipos()                      Sets the current record's "Caracteristicastecnicasequipos" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametrosensayosodu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametrosensayosodu');
        $this->hasColumn('parametrosensayosodu_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_ref', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('parametrosensayosodu_descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('parametrosensayosodu_modificado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('parametrosensayosodu_dcfs', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempoinicialestabilizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomaximoestabilizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempobajatension', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomaximobajatension', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomedicioncalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomaximomedicioncalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomedicionfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiemporecuperacionminima', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempomaximorecuperacionminima', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_delayarranquecompresor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempoapagadoentrecaloryfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempocierrevalvula1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempocierrevalvula2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_tiempofinal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presioninicialmin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presioninicialmax', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltapresionestabilizacionmin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltapresionestabilizacionmax', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_velocidadminbajatension', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltapresionbajatensionmin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltapresionbajatensionmax', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltatempmincalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltatempmaxcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_corrientemincalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_corrientemaxcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_potenciamincalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_potenciamaxcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_velocidadmaxventiladorcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_velocidadminventiladorcalor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presionminapagadocompresor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltatempminfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_deltatempmaxfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_corrientemaxfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_corrienteminfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_potenciaminfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_potenciamaxfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_velocidadminventiladorfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_velocidadmaxventiladorfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presionminfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presionmaxfrio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_presionmaxrecuperacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parametrosensayosodu_idversion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('es_activo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Versiones', array(
             'local' => 'parametrosensayosodu_idversion',
             'foreign' => 'versiones_id'));

        $this->hasMany('Caracteristicastecnicasequipos', array(
             'local' => 'parametrosensayosodu_id',
             'foreign' => 'caracteristicastecnicasequipos_idparametros_odu'));
    }
}