<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ensayoparametro', 'pcb');

/**
 * BaseEnsayoparametro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tag
 * @property integer $paso
 * @property float $valor
 * @property integer $ensayoid
 * @property Ensayo $Ensayo
 * 
 * @method integer         getId()       Returns the current record's "id" value
 * @method string          getTag()      Returns the current record's "tag" value
 * @method integer         getPaso()     Returns the current record's "paso" value
 * @method float           getValor()    Returns the current record's "valor" value
 * @method integer         getEnsayoid() Returns the current record's "ensayoid" value
 * @method Ensayo          getEnsayo()   Returns the current record's "Ensayo" value
 * @method Ensayoparametro setId()       Sets the current record's "id" value
 * @method Ensayoparametro setTag()      Sets the current record's "tag" value
 * @method Ensayoparametro setPaso()     Sets the current record's "paso" value
 * @method Ensayoparametro setValor()    Sets the current record's "valor" value
 * @method Ensayoparametro setEnsayoid() Sets the current record's "ensayoid" value
 * @method Ensayoparametro setEnsayo()   Sets the current record's "Ensayo" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnsayoparametro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ensayoparametro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('paso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valor', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ensayoid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ensayo', array(
             'local' => 'ensayoid',
             'foreign' => 'id'));
    }
}