<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EnsayoFallaControlada', 'doctrine');

/**
 * BaseEnsayoFallaControlada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ensayo_nro_serie
 * @property timestamp $fecha
 * @property integer $falla_controlada_id
 * @property integer $usuario_id
 * @property string $linea
 * @property string $dcf
 * @property FallaControlada $FallaControlada
 * @property SfGuardUser $SfGuardUser
 * 
 * @method integer               getId()                  Returns the current record's "id" value
 * @method string                getEnsayoNroSerie()      Returns the current record's "ensayo_nro_serie" value
 * @method timestamp             getFecha()               Returns the current record's "fecha" value
 * @method integer               getFallaControladaId()   Returns the current record's "falla_controlada_id" value
 * @method integer               getUsuarioId()           Returns the current record's "usuario_id" value
 * @method string                getLinea()               Returns the current record's "linea" value
 * @method string                getDcf()                 Returns the current record's "dcf" value
 * @method FallaControlada       getFallaControlada()     Returns the current record's "FallaControlada" value
 * @method SfGuardUser           getSfGuardUser()         Returns the current record's "SfGuardUser" value
 * @method EnsayoFallaControlada setId()                  Sets the current record's "id" value
 * @method EnsayoFallaControlada setEnsayoNroSerie()      Sets the current record's "ensayo_nro_serie" value
 * @method EnsayoFallaControlada setFecha()               Sets the current record's "fecha" value
 * @method EnsayoFallaControlada setFallaControladaId()   Sets the current record's "falla_controlada_id" value
 * @method EnsayoFallaControlada setUsuarioId()           Sets the current record's "usuario_id" value
 * @method EnsayoFallaControlada setLinea()               Sets the current record's "linea" value
 * @method EnsayoFallaControlada setDcf()                 Sets the current record's "dcf" value
 * @method EnsayoFallaControlada setFallaControlada()     Sets the current record's "FallaControlada" value
 * @method EnsayoFallaControlada setSfGuardUser()         Sets the current record's "SfGuardUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnsayoFallaControlada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ensayo_falla_controlada');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ensayo_nro_serie', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('falla_controlada_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('linea', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('dcf', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FallaControlada', array(
             'local' => 'falla_controlada_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}