<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EnsayoAltoPotencial', 'doctrine');

/**
 * BaseEnsayoAltoPotencial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nro_serie
 * @property string $orden_fabricacion
 * @property timestamp $fecha
 * @property integer $resultado
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getNroSerie()          Returns the current record's "nro_serie" value
 * @method string              getOrdenFabricacion()  Returns the current record's "orden_fabricacion" value
 * @method timestamp           getFecha()             Returns the current record's "fecha" value
 * @method integer             getResultado()         Returns the current record's "resultado" value
 * @method EnsayoAltoPotencial setId()                Sets the current record's "id" value
 * @method EnsayoAltoPotencial setNroSerie()          Sets the current record's "nro_serie" value
 * @method EnsayoAltoPotencial setOrdenFabricacion()  Sets the current record's "orden_fabricacion" value
 * @method EnsayoAltoPotencial setFecha()             Sets the current record's "fecha" value
 * @method EnsayoAltoPotencial setResultado()         Sets the current record's "resultado" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnsayoAltoPotencial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ensayo_alto_potencial');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nro_serie', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('orden_fabricacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('resultado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}