<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FallaControlada', 'doctrine');

/**
 * BaseFallaControlada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $es_idu
 * @property Doctrine_Collection $EnsayoFallaControlada
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getDescripcion()           Returns the current record's "descripcion" value
 * @method integer             getEsIdu()                 Returns the current record's "es_idu" value
 * @method Doctrine_Collection getEnsayoFallaControlada() Returns the current record's "EnsayoFallaControlada" collection
 * @method FallaControlada     setId()                    Sets the current record's "id" value
 * @method FallaControlada     setDescripcion()           Sets the current record's "descripcion" value
 * @method FallaControlada     setEsIdu()                 Sets the current record's "es_idu" value
 * @method FallaControlada     setEnsayoFallaControlada() Sets the current record's "EnsayoFallaControlada" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFallaControlada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('falla_controlada');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_idu', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EnsayoFallaControlada', array(
             'local' => 'id',
             'foreign' => 'falla_controlada_id'));
    }
}