<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Versiones', 'doctrine');

/**
 * BaseVersiones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $versiones_id
 * @property string $versiones_descripcion
 * @property Doctrine_Collection $Parametrosensayosidu
 * @property Doctrine_Collection $Parametrosensayosodu
 * 
 * @method integer             getVersionesId()           Returns the current record's "versiones_id" value
 * @method string              getVersionesDescripcion()  Returns the current record's "versiones_descripcion" value
 * @method Doctrine_Collection getParametrosensayosidu()  Returns the current record's "Parametrosensayosidu" collection
 * @method Doctrine_Collection getParametrosensayosodu()  Returns the current record's "Parametrosensayosodu" collection
 * @method Versiones           setVersionesId()           Sets the current record's "versiones_id" value
 * @method Versiones           setVersionesDescripcion()  Sets the current record's "versiones_descripcion" value
 * @method Versiones           setParametrosensayosidu()  Sets the current record's "Parametrosensayosidu" collection
 * @method Versiones           setParametrosensayosodu()  Sets the current record's "Parametrosensayosodu" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVersiones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('versiones');
        $this->hasColumn('versiones_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('versiones_descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '"',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parametrosensayosidu', array(
             'local' => 'versiones_id',
             'foreign' => 'parametrosensayosidu_idversion'));

        $this->hasMany('Parametrosensayosodu', array(
             'local' => 'versiones_id',
             'foreign' => 'parametrosensayosodu_idversion'));
    }
}